### ISSUE TITLE
Sweep: Add a readme explaining what this repo does

### ISSUE THREAD

**Issue by william-redenbaugh** [william-redenbaugh/TeensyOSCSAL#1]
<details open>
<summary>Checklist</summary>

- [X] `README.md`
> • Start the README with a brief overview of the repository. Mention that the repository is a Software Abstraction library that unifies OS calls across all platforms. Its aim is to increase code re-use.
> • Provide instructions on how to install or use the library. Include any prerequisites or dependencies. Mention that the library is written in C++ and requires a C++ compiler to build and run.
> • Provide a brief overview of each of the main files in the repository. For each file, describe what it does and how it contributes to the overall functionality of the library. The main files to cover are: os_mutx.cpp, os_queue.cpp, os_sem.cpp, os_setbits.cpp, os_thread.cpp, and teensyos_csal_defs.h.
> • Include a section on how to contribute to the repository. Mention that contributors can submit issues, create pull requests, and follow the general workflow for contributing. Provide a link to the issues page of the repository.

</details>

**Comment by william-redenbaugh** [comment]
Sweep: Mention that the module relies on CSAL Shared: https://github.com/william-redenbaugh/CSAL_SHARED and is just a library that needs to be included with other modules.  Also mention that an example can be found here: https://github.com/william-redenbaugh/TeensyOSExamples

**Comment by pranavmreddy** [comment]
@william-redenbaugh Did this not generate the readme correctly?
